from datetime import datetime
from typing import Optional, List
from sqlalchemy import Integer, String, Float, Text, ForeignKey, DateTime
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.core.database import Base

class Review(Base):
    __tablename__ = "reviews"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    pull_request_id: Mapped[int] = mapped_column(Integer, ForeignKey("pull_requests.id", ondelete="CASCADE"), nullable=False)
    
    status: Mapped[str] = mapped_column(String, default="pending")  # pending, running, completed, failed
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Markdown overall summary report
    
    # Quantitative Quality Metrics
    bug_count: Mapped[int] = mapped_column(Integer, default=0)
    security_count: Mapped[int] = mapped_column(Integer, default=0)
    performance_count: Mapped[int] = mapped_column(Integer, default=0)
    clean_code_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # 0 - 100 Quality Health Score (generated by LLM Synthesizer based on findings)
    score: Mapped[int] = mapped_column(Integer, default=100)
    
    duration_seconds: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    pull_request = relationship("PullRequest", back_populates="reviews")
    comments = relationship("ReviewComment", back_populates="review", cascade="all, delete-orphan")

class ReviewComment(Base):
    __tablename__ = "review_comments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    review_id: Mapped[int] = mapped_column(Integer, ForeignKey("reviews.id", ondelete="CASCADE"), nullable=False)
    
    file_path: Mapped[str] = mapped_column(String, nullable=False)
    line_number: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)  # New line number in PR
    diff_hunk: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # The diff segment
    
    # Meta categories
    category: Mapped[str] = mapped_column(String, default="style")  # bug, security, performance, style
    severity: Mapped[str] = mapped_column(String, default="info")  # info, warning, critical
    
    # Review details
    title: Mapped[str] = mapped_column(String, nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)  # Markdown text explaining the issue
    
    # Direct suggestions
    suggestion: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Suggestion code block
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    review = relationship("Review", back_populates="comments")
