import os
import json
import re
from typing import List, Dict, Any, Optional
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from backend.app.core.config import settings

def get_llm():
    """
    Initializes and returns the ChatGroq LLM model.
    Falls back to None if API Key is not set.
    """
    if settings.DEMO_MODE or not settings.GROQ_API_KEY:
        return None
    try:
        return ChatGroq(
            api_key=settings.GROQ_API_KEY,
            model_name=settings.GROQ_MODEL,
            temperature=0.1  # Low temperature for highly precise code review analysis
        )
    except Exception as e:
        print(f"Failed to initialize ChatGroq client: {e}")
        return None

def clean_json_string(text: str) -> str:
    """
    Strips markdown code fence wrappers from JSON outputs if generated by the LLM.
    """
    text = text.strip()
    # Strip opening ```json or ``` blocks
    text = re.sub(r'^```(?:json)?\s*', '', text)
    # Strip closing ``` block
    text = re.sub(r'\s*```$', '', text)
    return text.strip()

async def query_rag_for_diff(state: Dict[str, Any], file_path: str, diff_content: str) -> str:
    """
    Queries local ChromaDB vector database using the diff changes as a query,
    retrieving helper classes, db schemas, or configurations to supply global context.
    """
    if settings.DEMO_MODE:
        return "[RAG Context]: Found stripe client configurations and database schemas matching payment service."

    from backend.app.services.vector_db import VectorDBService

    vector_service = VectorDBService()
    safe_query = f"File: {file_path}. Changes: {diff_content[:300]}"
    try:
        matches = await vector_service.search_codebase(state["repository_full_name"], safe_query, k=2)
        if not matches:
            return "No additional codebase context found."
            
        context_str = "### Global Codebase Context (Retrieved via ChromaDB RAG):\n"
        for m in matches:
            context_str += f"\n- **Match in {m['file_path']}** (relevance score: {m['score']}):\n```\n{m['content'][:400]}\n```\n"
        return context_str
    except Exception as e:
        return f"Error loading RAG context: {e}"

def generate_mock_comments(category: str, file_path: str) -> List[Dict[str, Any]]:
    """
    Generates high-fidelity simulated comments for Demo Mode.
    Specifically targets services/payment_service.py from the mock diff!
    """
    comments = []
    
    if "payment_service.py" in file_path:
        if category == "bug":
            comments.append({
                "file_path": file_path,
                "line_number": 15,
                "diff_hunk": "@@ -1,15 +1,28 @@\n+        # BUG RISK: If token is empty or invalid, stripe raises card error\n+        # SECURITY RISK: Printing raw stripe token to log files!\n+        print(f\"Processing charge for amount: {amount} with token: {token}\")",
                "category": "bug",
                "severity": "critical",
                "title": "Uncaught Card Declines & Token Failures",
                "body": "If the `token` argument is invalid or empty, the `stripe.Charge.create` call will immediately raise a `stripe.error.CardError` or a validation exception. While there is a try-except block, returning a generic error output directly does not validate or sanitize inputs beforehand.",
                "suggestion": "if not token or not token.startswith('tok_'):\n    raise ValueError(\"Invalid payment token structure\")"
            })
            comments.append({
                "file_path": file_path,
                "line_number": 17,
                "diff_hunk": "@@ -1,15 +1,28 @@\n+        if amount <= 0:\n+            raise ValueError(\"Amount must be greater than zero\")",
                "category": "bug",
                "severity": "warning",
                "title": "Missing Explicit Currency/Limit Assertions",
                "body": "Stripe requires payments to be above a minimum limit (e.g., 50 cents in USD). Simply checking if `amount <= 0` does not check if the minimum cent limit is satisfied, which could result in direct rejection from Stripe APIs.",
                "suggestion": "if amount < 50:\n    raise ValueError(\"Stripe charge amount must be at least 50 cents (USD)\")"
            })
        elif category == "security":
            comments.append({
                "file_path": file_path,
                "line_number": 14,
                "diff_hunk": "@@ -1,15 +1,28 @@\n+        # BUG RISK: If token is empty or invalid, stripe raises card error\n+        # SECURITY RISK: Printing raw stripe token to log files!\n+        print(f\"Processing charge for amount: {amount} with token: {token}\")",
                "category": "security",
                "severity": "critical",
                "title": "Sensitive Token Leakage in Application Logs",
                "body": "Logging or printing raw Stripe client source tokens (`token`) exposes sensitive payment data in plain text. If logs are collected by external processors (e.g. Datadog, Logstash), this violates PCI-DSS compliance regulations.",
                "suggestion": "# Sanitize or obfuscate the token in logging output\nobfuscated_token = token[:8] + \"*\" * (len(token) - 8) if token else \"None\"\nlogger.info(f\"Processing charge for amount: {amount} with token: {obfuscated_token}\")"
            })
        elif category == "performance":
            comments.append({
                "file_path": file_path,
                "line_number": 21,
                "diff_hunk": "@@ -1,15 +1,28 @@\n+        # PERFORMANCE RISK: Executing stripe call synchronously in async backend\n+        charge = stripe.Charge.create(",
                "category": "performance",
                "severity": "warning",
                "title": "Blocking Synchronous Network Request",
                "body": "Invoking `stripe.Charge.create` in a synchronous call blocks the main thread in an asynchronous FastAPI server. Under heavy concurrent traffic, this causes drastic degradation of throughput, turning a sub-second response into seconds of delay.",
                "suggestion": "# Wrap the blocking synchronous call inside an executor, or use await stripe.Charge.create_async if using newer Stripe clients\nimport asyncio\nloop = asyncio.get_event_loop()\ncharge = await loop.run_in_executor(\n    None,\n    lambda: stripe.Charge.create(\n        amount=int(amount),\n        currency=\"usd\",\n        source=token,\n        description=\"Charge for purchase\"\n    )\n)"
            })
        elif category == "style":
            comments.append({
                "file_path": file_path,
                "line_number": 6,
                "diff_hunk": "@@ -1,15 +1,28 @@\n+logger = logging.getLogger(__name__)\n stripe.api_key = os.getenv(\"STRIPE_SECRET_KEY\")",
                "category": "style",
                "severity": "info",
                "title": "Use Dependency Injection for Secret Configurations",
                "body": "Retrieving API secrets directly via `os.getenv` inside functions violates clean architecture principles and hampers mock testing. It is cleaner to load secrets once in central configurations and pass them down or inject them.",
                "suggestion": "from backend.app.core.config import settings\nstripe.api_key = settings.STRIPE_SECRET_KEY"
            })
            
    return comments
